/**
 * Manual compile + upload for a production that has assets but never compiled.
 * Usage: npx tsx scripts/manual-compile-upload.ts <productionId>
 */
import { config } from 'dotenv';
import { resolve, join, dirname } from 'path';
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, '..');
config({ path: resolve(PROJECT_ROOT, '.env') });

import { compileMusicOnlyVideo } from '../src/services/ffmpeg-service.js';
import { uploadVideo } from '../src/services/youtube-service.js';
import { AssetManifest } from '../src/types/index.js';

const productionId = process.argv[2];
if (!productionId) {
  console.error('Usage: npx tsx scripts/manual-compile-upload.ts <productionId>');
  process.exit(1);
}

const channelSlug = 'ch-liminal-synth';
const channelDir = join(PROJECT_ROOT, 'projects', channelSlug);
const outputDir = join(channelDir, 'output', productionId);
const oauthPath = join(channelDir, '.youtube-oauth.json');

async function main(): Promise<void> {
  // Load asset manifest
  const manifest: AssetManifest = JSON.parse(
    await readFile(join(outputDir, 'asset-manifest.json'), 'utf-8')
  );

  console.log(`Compiling ${manifest.animations.length} segment(s)...`);

  // Compile with vignette filter (Liminal Synth preset)
  const result = await compileMusicOnlyVideo(outputDir, manifest, '1920x1080', 'synthwave');
  console.log(`Compiled: ${result.videoPath} (${result.durationSeconds}s, ${result.fileSizeMb}MB)`);

  // Upload to YouTube as unlisted (test)
  console.log('Uploading to YouTube (unlisted)...');
  const ytResult = await uploadVideo(oauthPath, {
    title: 'Liminal Synth — E2E Pipeline Test',
    description: 'End-to-end pipeline test for Liminal Synth music-only channel.\n\nGenerated by YT_Channel_Auto pipeline.',
    tags: ['liminal synth', 'dark ambient', 'synthwave', 'electronic'],
    hashtags: ['#LiminalSynth', '#DarkAmbient'],
    videoPath: result.videoPath,
    privacy: 'unlisted',
  });

  console.log(`Uploaded! Video ID: ${ytResult.videoId}`);
  console.log(`URL: https://youtube.com/watch?v=${ytResult.videoId}`);
}

main().catch((err) => {
  console.error('Failed:', err);
  process.exit(1);
});
